[versions]
...
...
recyclerview = "1.3.2"
glide = "4.12.0"
circle = "3.1.0"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"


[libraries]
...
...
ndroid-glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
android-circle-image = { group = "de.hdodenhof:circleimageview", name = "circle", version.ref = "circle" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }


[plugins]
...
...
...

